"""User table fields added

Revision ID: f2547705448a
Revises: b96d2cab2954
Create Date: 2024-11-11 13:58:34.875862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2547705448a'
down_revision: Union[str, None] = 'b96d2cab2954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
